# Generated by Django 2.2.6 on 2019-11-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField(choices=[(1, '卸部門'), (2, '加工部門'), (3, '配送部'), (4, '観光通り店'), (5, 'カロム店'), (6, '思案橋店'), (7, 'ブライダル')], verbose_name='店舗')),
                ('sale_date', models.DateField(default=datetime.datetime(2019, 11, 1, 18, 13, 16, 476044), verbose_name='売上日')),
                ('sale', models.IntegerField(verbose_name='売上額')),
                ('cost', models.IntegerField(verbose_name='仕入額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '売上',
                'verbose_name_plural': '売上',
            },
        ),
    ]
