# Generated by Django 2.2.6 on 2019-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField(choices=[(1, '卸部門'), (2, '加工部門'), (3, '配送部'), (4, '観光通り店'), (5, 'カロム店'), (6, '思案橋店'), (7, 'ブライダル')], default=1, verbose_name='店舗')),
                ('sale_date', models.DateField(verbose_name='売上日')),
                ('sale', models.IntegerField(verbose_name='売上額')),
                ('cost', models.IntegerField(verbose_name='仕入額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
