# Generated by Django 2.2.6 on 2019-10-29 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191025_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': '売上', 'verbose_name_plural': '売上'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 29, 11, 26, 6, 254960), verbose_name='売上日'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='store',
            field=models.IntegerField(choices=[(1, '卸部門'), (2, '加工部門'), (3, '配送部'), (4, '観光通り店'), (5, 'カロム店'), (6, '思案橋店'), (7, 'ブライダル')], verbose_name='店舗'),
        ),
    ]
