# Generated by Django 2.2.6 on 2019-10-29 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191029_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 29, 11, 52, 34, 581767), verbose_name='売上日'),
        ),
    ]
